package models

// ParsedData holds the data extracted from an uploaded file.
// The fields are based on the `ParsedData` interface in the frontend TypeScript code.
// Using pointers for most fields to handle missing values gracefully.

type ParsedData struct {
	Mrn                               *string  `json:"mrn,omitempty"`
	Name                              *string  `json:"name,omitempty"`
	Dob                               *string  `json:"dob,omitempty"`
	ReportDate                        *string  `json:"report_date,omitempty"`
	MdcIdcDevSerialNumber             *string  `json:"mdc_idc_dev_serial_number,omitempty"`
	MdcIdcDevModel                    *string  `json:"mdc_idc_dev_model,omitempty"`
	MdcIdcDevManufacturer             *string  `json:"mdc_idc_dev_manufacturer,omitempty"`
	MdcIdcDevImplantDate              *string  `json:"mdc_idc_dev_implant_date,omitempty"`
	MdcIdcDevRaSerialNumber           *string  `json:"mdc_idc_dev_ra_serial_number,omitempty"`
	MdcIdcDevRaManufacturer           *string  `json:"mdc_idc_dev_ra_manufacturer,omitempty"`
	MdcIdcDevRaModel                  *string  `json:"mdc_idc_dev_ra_model,omitempty"`
	MdcIdcDevRaImplantDate            *string  `json:"mdc_idc_dev_ra_implant_date,omitempty"`
	MdcIdcDevRvSerialNumber           *string  `json:"mdc_idc_dev_rv_serial_number,omitempty"`
	MdcIdcDevRvManufacturer           *string  `json:"mdc_idc_dev_rv_manufacturer,omitempty"`
	MdcIdcDevRvModel                  *string  `json:"mdc_idc_dev_rv_model,omitempty"`
	MdcIdcDevRvImplantDate            *string  `json:"mdc_idc_dev_rv_implant_date,omitempty"`
	MdcIdcDevLvSerialNumber           *string  `json:"mdc_idc_dev_lv_serial_number,omitempty"`
	MdcIdcDevLvManufacturer           *string  `json:"mdc_idc_dev_lv_manufacturer,omitempty"`
	MdcIdcDevLvModel                  *string  `json:"mdc_idc_dev_lv_model,omitempty"`
	MdcIdcDevLvImplantDate            *string  `json:"mdc_idc_dev_lv_implant_date,omitempty"`
	MdcIdcMsmtHvImpedanceMean         *string  `json:"mdc_idc_msmt_hv_impedance_mean,omitempty"`
	MdcIdcStatAtafBurdenPercent       *string  `json:"mdc_idc_stat_ataf_burden_percent,omitempty"`
	MdcIdcStatAtafCount               *string  `json:"mdc_idc_stat_ataf_count,omitempty"`
	MdcIdcStatPvcCount                *string  `json:"mdc_idc_stat_pvc_count,omitempty"`
	MdcIdcStatNsvtCount               *string  `json:"mdc_idc_stat_nsvt_count,omitempty"`
	MdcIdcStatAtpDeliveredRecent      *string  `json:"mdc_idc_stat_atp_delivered_recent,omitempty"`
	MdcIdcStatShocksDeliveredRecent   *string  `json:"mdc_idc_stat_shocks_delivered_recent,omitempty"`
	MdcIdcSetBradyMode                *string  `json:"mdc_idc_set_brady_mode,omitempty"`
	MdcIdcSetBradyLowrate             *string  `json:"mdc_idc_set_brady_lowrate,omitempty"`
	MdcIdcSetBradyMaxTrackingRate     *string  `json:"mdc_idc_set_brady_max_tracking_rate,omitempty"`
	MdcIdcSetBradyMaxSensorRate       *string  `json:"mdc_idc_set_brady_max_sensor_rate,omitempty"`
	MdcIdcSetBradyModeSwitchRate      *string  `json:"mdc_idc_set_brady_mode_switch_rate,omitempty"`
	MdcIdcDevSav                      *string  `json:"mdc_idc_dev_sav,omitempty"`
	MdcIdcDevPav                      *string  `json:"mdc_idc_dev_pav,omitempty"`
	MdcIdcStatBradyRaPercentPaced     *string  `json:"mdc_idc_stat_brady_ra_percent_paced,omitempty"`
	MdcIdcStatBradyRvPercentPaced     *string  `json:"mdc_idc_stat_brady_rv_percent_paced,omitempty"`
	MdcIdcStatBradyLvPercentPaced     *string  `json:"mdc_idc_stat_brady_lv_percent_paced,omitempty"`
	MdcIdcStatBradyBivPercentPaced    *string  `json:"mdc_idc_stat_brady_biv_percent_paced,omitempty"`
	MdcIdcBattPercentage              *string  `json:"mdc_idc_batt_percentage,omitempty"`
	MdcIdcBattVolt                    *string  `json:"mdc_idc_batt_volt,omitempty"`
	MdcIdcBattRemaining               *string  `json:"mdc_idc_batt_remaining,omitempty"`
	MdcIdcBattStatus                  *string  `json:"mdc_idc_batt_status,omitempty"`
	MdcIdcCapChargeTime               *string  `json:"mdc_idc_cap_charge_time,omitempty"`
	MdcIdcMsmtRaImpedanceMean         *string  `json:"mdc_idc_msmt_ra_impedance_mean,omitempty"`
	MdcIdcMsmtRaSensingMean           *string  `json:"mdc_idc_msmt_ra_sensing_mean,omitempty"`
	MdcIdcMsmtRaPacingThreshold       *string  `json:"mdc_idc_msmt_ra_pacing_threshold,omitempty"`
	MdcIdcMsmtRaPw                    *string  `json:"mdc_idc_msmt_ra_pw,omitempty"`
	MdcIdcMsmtRvImpedanceMean         *string  `json:"mdc_idc_msmt_rv_impedance_mean,omitempty"`
	MdcIdcMsmtRvSensingMean           *string  `json:"mdc_idc_msmt_rv_sensing_mean,omitempty"`
	MdcIdcMsmtRvPacingThreshold       *string  `json:"mdc_idc_msmt_rv_pacing_threshold,omitempty"`
	MdcIdcMsmtRvPw                    *string  `json:"mdc_idc_msmt_rv_pw,omitempty"`
	MdcIdcMsmtLvImpedanceMean         *string  `json:"mdc_idc_msmt_lv_impedance_mean,omitempty"`
	MdcIdcMsmtLvSensingMean           *string  `json:"mdc_idc_msmt_lv_sensing_mean,omitempty"`
	MdcIdcMsmtLvPacingThreshold       *string  `json:"mdc_idc_msmt_lv_pacing_threshold,omitempty"`
	MdcIdcMsmtLvPw                    *string  `json:"mdc_idc_msmt_lv_pw,omitempty"`
	VT1Active                         *string  `json:"VT1_active,omitempty"`
	VT1DetectionInterval              *string  `json:"VT1_detection_interval,omitempty"`
	VT1Therapy1Atp                    *string  `json:"VT1_therapy_1_atp,omitempty"`
	VT1Therapy1NoBursts               *string  `json:"VT1_therapy_1_no_bursts,omitempty"`
	VT1Therapy2Atp                    *string  `json:"VT1_therapy_2_atp,omitempty"`
	VT1Therapy2NoBursts               *string  `json:"VT1_therapy_2_no_bursts,omitempty"`
	VT1Therapy3Energy                 *string  `json:"VT1_therapy_3_energy,omitempty"`
	VT1Therapy4Energy                 *string  `json:"VT1_therapy_4_energy,omitempty"`
	VT1Therapy5Energy                 *string  `json:"VT1_therapy_5_energy,omitempty"`
	VT1Therapy5MaxNumShocks           *string  `json:"VT1_therapy_5_max_num_shocks,omitempty"`
	VT2Active                         *string  `json:"VT2_active,omitempty"`
	VT2DetectionInterval              *string  `json:"VT2_detection_interval,omitempty"`
	VT2Therapy1Atp                    *string  `json:"VT2_therapy_1_atp,omitempty"`
	VT2Therapy1NoBursts               *string  `json:"VT2_therapy_1_no_bursts,omitempty"`
	VT2Therapy2Atp                    *string  `json:"VT2_therapy_2_atp,omitempty"`
	VT2Therapy2NoBursts               *string  `json:"VT2_therapy_2_no_bursts,omitempty"`
	VT2Therapy3Energy                 *string  `json:"VT2_therapy_3_energy,omitempty"`
	VT2Therapy4Energy                 *string  `json:"VT2_therapy_4_energy,omitempty"`
	VT2Therapy5Energy                 *string  `json:"VT2_therapy_5_energy,omitempty"`
	VT2Therapy5MaxNumShocks           *string  `json:"VT2_therapy_5_max_num_shocks,omitempty"`
	VFActive                          *string  `json:"VF_active,omitempty"`
	VFDetectionInterval               *string  `json:"VF_detection_interval,omitempty"`
	VFTherapy1Atp                     *string  `json:"VF_therapy_1_atp,omitempty"`
	VFTherapy2Energy                  *string  `json:"VF_therapy_2_energy,omitempty"`
	VFTherapy3Energy                  *string  `json:"VF_therapy_3_energy,omitempty"`
	VFTherapy4Energy                  *string  `json:"VF_therapy_4_energy,omitempty"`
	VFTherapy4MaxNumShocks            *string  `json:"VF_therapy_4_max_num_shocks,omitempty"`
	EmbeddedPdfBase64                 *string  `json:"embeddedPdfBase64,omitempty"`
	EmbeddedPdfName                   *string  `json:"embeddedPdfName,omitempty"`
}
